"""create_table_users_posts_categories_comments

Revision ID: 3dc98227df61
Revises: 
Create Date: 2023-10-14 20:07:59.230977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc98227df61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('etiquetaCategoria', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('idCategoria')
    )
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('nombreUsuario', sa.String(length=100), nullable=False),
    sa.Column('correoElectronico', sa.String(length=100), nullable=False),
    sa.Column('contrasenia', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('correoElectronico')
    )
    op.create_table('entrada',
    sa.Column('idEntrada', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('autorEntrada', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=300), nullable=False),
    sa.Column('fechaEntrada', sa.Date(), nullable=False),
    sa.Column('idCategoriaEntrada', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autorEntrada'], ['usuario.idUsuario'], ),
    sa.ForeignKeyConstraint(['idCategoriaEntrada'], ['categoria.idCategoria'], ),
    sa.PrimaryKeyConstraint('idEntrada')
    )
    op.create_table('comentario',
    sa.Column('idComentario', sa.Integer(), nullable=False),
    sa.Column('textoComentario', sa.String(length=100), nullable=False),
    sa.Column('fechaComentario', sa.Date(), nullable=False),
    sa.Column('autorComentario', sa.Integer(), nullable=False),
    sa.Column('idEntradaComentario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autorComentario'], ['usuario.idUsuario'], ),
    sa.ForeignKeyConstraint(['idEntradaComentario'], ['entrada.idEntrada'], ),
    sa.PrimaryKeyConstraint('idComentario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    op.drop_table('entrada')
    op.drop_table('usuario')
    op.drop_table('categoria')
    # ### end Alembic commands ###
